### ISSUE TITLE
App no longer working?

### ISSUE THREAD

**Issue by Leader2light** [mike-ward/tweetz-desktop#29]
My feeds stopped working about 4 hours ago.  I signed out and now when I go to sign back in there is an error/crash report.  

---------------------------

---------------------------
Tweetz Desktop Crash Report

Date: 2019-07-29 22:26:26Z

Version: 1.3.3

-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------

Operation System Information

-----------------------------------------------------------------

Windows 10 Enterprise

Service Pack: No Service Pack detected

Exception

-----------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.

   at tweetz5.Controls.Authenticate.<GetPin_OnClick>d__5.MoveNext() in C:\Users\mike\GitHub\tweetz-desktop\tweetz\tweetz5\Controls\Authenticate.xaml.cs:line 36

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

---------------------------
OK   
---------------------------

**Comment by timcin** [comment]
Same thing happened to me 4 hrs ago.

**Comment by Leader2light** [comment]
Something must have changed with twitter API?  I really hope you can get this working again.

**Comment by sahya** [comment]
Maybe, twitter changed http policy must be using TLS1.2.

**Comment by mistabob** [comment]
Yep, little Tweetz ain't chirping no more... I first thought, Twitter had me banned because of a little nasty Tweet I wrote to / about Boris Johnson, by far, the worst PM Britain has ever seen, containing a self-made make-fun-o-him-pic ...

(https://pbs.twimg.com/media/EAY6XSDW4AURUi3.jpg)

The censorship nowadays is so massive, that if you're not "political correct" enough, you're account will be toast in minutes.

**Comment by Leader2light** [comment]
I can't find any app that has similar functionality to this one.   I actually don't use twitter for anything other than just looking at my feed in tweetz.  I love it just starts with windows and opens on my 2nd monitor.

**Comment by duedipicche** [comment]
My feeds stopped working about 2 hours ago. I signed out and now when I go to sign back in there is an error/crash report.
I also tried uninstalling and reinstalling, but it still doesn't work.
---------------------------
---------------------------
Tweetz Desktop Crash Report

Date: 2019-07-30 11:50:37Z

Version: 1.3.3
----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------



Operation System Information

-----------------------------------------------------------------

Windows 7 Home Premium

Service Pack: Service Pack 1





Exception

-----------------------------------------------------------------

System.NullReferenceException: Riferimento a un oggetto non impostato su un'istanza di oggetto.

   in tweetz5.Controls.Authenticate.<GetPin_OnClick>d__5.MoveNext() in C:\Users\mike\GitHub\tweetz-desktop\tweetz\tweetz5\Controls\Authenticate.xaml.cs:riga 36

--- Fine traccia dello stack da posizione precedente dove è stata generata l'eccezione ---

   in System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


---------------------------
OK   
---------------------------

**Comment by phrozact** [comment]
Same here, app just stopped working  for me. Was working fine less than 24 hours ago. I signed out and when I clicked on "Get PIN", the app crashed. 

This is the error message:

---------------------------

---------------------------
Tweetz Desktop Crash Report

Date: 2019-07-30 12:55:38Z

Version: 1.3.3



-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------



Operation System Information

-----------------------------------------------------------------

Windows 10 Home

Service Pack: No Service Pack detected





Exception

-----------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.

   at tweetz5.Controls.Authenticate.<GetPin_OnClick>d__5.MoveNext() in C:\Users\mike\GitHub\tweetz-desktop\tweetz\tweetz5\Controls\Authenticate.xaml.cs:line 36

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


---------------------------
OK   
---------------------------

**Comment by ScottYates** [comment]
Adding my voice to the din.  I hope dearly for a fix because (as others have stated, this is the only app that works so well).  

Thank you for providing it, and good luck with the fix!

---------------------------

---------------------------
Tweetz Desktop Crash Report

Date: 2019-07-30 13:48:31Z

Version: 1.2.4



-----------------------------------------------------------------

*** Pressing Ctrl+C will copy the contents of this dialog ***

*** Email to: mike@mike-ward.net ***

-----------------------------------------------------------------



Operation System Information

-----------------------------------------------------------------

Windows 10 Enterprise

Service Pack: No Service Pack detected





Exception

-----------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.

   at tweetz5.Controls.Authenticate.<GetPin_OnClick>d__5.MoveNext() in C:\Users\mike\GitHub\tweetz-desktop\tweetz\tweetz5\Controls\Authenticate.xaml.cs:line 36

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


---------------------------
OK   
---------------------------

**Comment by osarusamba** [comment]
Latest twitter API seems to require TLS 1.2.
Plz update.

**Comment by darkufo** [comment]
Same here

**Comment by sahya** [comment]
I think following link is useful.
https://github.com/linvi/tweetinvi/issues/891#issuecomment-516460834

## Need to use
* library: .Net framework 4.6 by web.config
* SSL connection; Over TLS 1.2 
> Alternate, code-based solution for older runtimes:
> `System.Net.ServicePointManager.SecurityProtocol |= System.Net.SecurityProtocolType.Tls12;`

He may give up on this application development if this problem is not solved.
Actually, he is sad on Twitter.
https://twitter.com/mikeward_aa/status/1156192723784949764

Please write down your pull request fix issue.  please would you help us.
I want to keep using this application. It difficult to coding for me.

**Comment by mike-ward** [comment]
Hey, that worked! I'll post a new release shortly

**Comment by mike-ward** [comment]
OK, 1.3.4 published. Thanks for running that down.

**Comment by sahya** [comment]
Thank a lot !😉
Your release app working fine.🥰
